PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^ContestItem/', include('apps.ContestItem.urls', namespace='ContestItem')),  # 比赛项目模块
    url(r'^Contest/', include('apps.Contest.urls', namespace='Contest')),  # 比赛模块
    url(r'^SignUp/', include('apps.SignUp.urls', namespace='SignUp')),  # 学生报名模块
    url(r'^Court/', include('apps.Court.urls', namespace='Court')),  # 赛场安排模块
    url(r'^ContestPlace/', include('apps.ContestPlace.urls', namespace='ContestPlace')),  # 比赛场地模块
    url(r'^Jifen/', include('apps.Jifen.urls', namespace='Jifen')),  # 比赛积分模块
    url(r'^DoctorTeam/', include('apps.DoctorTeam.urls', namespace='DoctorTeam')),  # 医护团队模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/ContestPlace/urls.py
from apps.ContestPlace.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'ContestPlace'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<placeNo>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<placeNo>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<placeNo>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<placeNo>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,\
    PersonStatisticView,CourtStatisticView,JifenStatisticView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^personStatistic$', PersonStatisticView.as_view(), name='main'),  # 报名人数统计
    url(r'^courtStatistic$', CourtStatisticView.as_view(), name='main'),  # 场次数量统计
    url(r'^jifenStatistic$', JifenStatisticView.as_view(), name='main'),  # 比赛积分统计
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/ContestPlace/models.py
from django.db import models
from apps.ContestItem.models import ContestItem


class ContestPlace(models.Model):
    placeNo = models.CharField(max_length=20, default='', primary_key=True, verbose_name='场地编号')
    contestItemObj = models.ForeignKey(ContestItem,  db_column='contestItemObj', on_delete=models.PROTECT, verbose_name='运动项目')
    placeName = models.CharField(max_length=20, default='', verbose_name='场地名称')
    placeArea = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='场地面积')
    placePhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='场地照片')
    useDate = models.CharField(max_length=20, default='', verbose_name='投入使用时间')
    placeDesc = models.CharField(max_length=800, default='', verbose_name='场地描述')

    class Meta:
        db_table = 't_ContestPlace'
        verbose_name = '比赛场地信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        contestPlace = {
            'placeNo': self.placeNo,
            'contestItemObj': self.contestItemObj.className,
            'contestItemObjPri': self.contestItemObj.classId,
            'placeName': self.placeName,
            'placeArea': self.placeArea,
            'placePhoto': self.placePhoto.url,
            'useDate': self.useDate,
            'placeDesc': self.placeDesc,
        }
        return contestPlace


PythonProject/apps/ContestPlace/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.ContestPlace.models import ContestPlace
from apps.ContestItem.models import ContestItem
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台比赛场地添加
    def primaryKeyExist(self, placeNo):  # 判断主键是否存在
        try:
            ContestPlace.objects.get(placeNo=placeNo)
            return True
        except ContestPlace.DoesNotExist:
            return False

    def get(self,request):
        contestItems = ContestItem.objects.all()  # 获取所有比赛项目
        context = {
            'contestItems': contestItems,
        }

        # 使用模板
        return render(request, 'ContestPlace/contestPlace_frontAdd.html', context)

    def post(self, request):
        placeNo = request.POST.get('contestPlace.placeNo') # 判断场地编号是否存在
        if self.primaryKeyExist(placeNo):
            return JsonResponse({'success': False, 'message': '场地编号已经存在'})

        contestPlace = ContestPlace() # 新建一个比赛场地对象然后获取参数
        contestPlace.placeNo = placeNo
        contestPlace.contestItemObj = ContestItem.objects.get(classId=request.POST.get('contestPlace.contestItemObj.classId'))
        contestPlace.placeName = request.POST.get('contestPlace.placeName')
        contestPlace.placeArea = float(request.POST.get('contestPlace.placeArea'))
        try:
            contestPlace.placePhoto = self.uploadImageFile(request,'contestPlace.placePhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        contestPlace.useDate = request.POST.get('contestPlace.useDate')
        contestPlace.placeDesc = request.POST.get('contestPlace.placeDesc')
        contestPlace.save() # 保存比赛场地信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改比赛场地
    def get(self, request, placeNo):
        context = {'placeNo': placeNo}
        return render(request, 'ContestPlace/contestPlace_frontModify.html', context)


class FrontListView(BaseView):  # 前台比赛场地查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        placeNo = self.getStrParam(request, 'placeNo')
        contestItemObj_classId = self.getIntParam(request, 'contestItemObj.classId')
        placeName = self.getStrParam(request, 'placeName')
        useDate = self.getStrParam(request, 'useDate')
        # 然后条件组合查询过滤
        contestPlaces = ContestPlace.objects.all()
        if placeNo != '':
            contestPlaces = contestPlaces.filter(placeNo__contains=placeNo)
        if contestItemObj_classId != '0':
            contestPlaces = contestPlaces.filter(contestItemObj=contestItemObj_classId)
        if placeName != '':
            contestPlaces = contestPlaces.filter(placeName__contains=placeName)
        if useDate != '':
            contestPlaces = contestPlaces.filter(useDate__contains=useDate)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(contestPlaces, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        contestPlaces_page = self.paginator.page(self.currentPage)

        # 获取所有比赛项目
        contestItems = ContestItem.objects.all()
        # 构造模板需要的参数
        context = {
            'contestItems': contestItems,
            'contestPlaces_page': contestPlaces_page,
            'placeNo': placeNo,
            'contestItemObj_classId': int(contestItemObj_classId),
            'placeName': placeName,
            'useDate': useDate,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'ContestPlace/contestPlace_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示比赛场地详情页
    def get(self, request, placeNo):
        # 查询需要显示的比赛场地对象
        contestPlace = ContestPlace.objects.get(placeNo=placeNo)
        context = {
            'contestPlace': contestPlace
        }
        # 渲染模板显示
        return render(request, 'ContestPlace/contestPlace_frontshow.html', context)


class ListAllView(View): # 前台查询所有比赛场地
    def get(self,request):
        contestPlaces = ContestPlace.objects.all()
        contestPlaceList = []
        for contestPlace in contestPlaces:
            contestPlaceObj = {
                'placeNo': contestPlace.placeNo,
                'placeName': contestPlace.placeName,
            }
            contestPlaceList.append(contestPlaceObj)
        return JsonResponse(contestPlaceList, safe=False)


class UpdateView(BaseView):  # Ajax方式比赛场地更新
    def get(self, request, placeNo):
        # GET方式请求查询比赛场地对象并返回比赛场地json格式
        contestPlace = ContestPlace.objects.get(placeNo=placeNo)
        return JsonResponse(contestPlace.getJsonObj())

    def post(self, request, placeNo):
        # POST方式提交比赛场地修改信息更新到数据库
        contestPlace = ContestPlace.objects.get(placeNo=placeNo)
        contestPlace.contestItemObj = ContestItem.objects.get(classId=request.POST.get('contestPlace.contestItemObj.classId'))
        contestPlace.placeName = request.POST.get('contestPlace.placeName')
        contestPlace.placeArea = float(request.POST.get('contestPlace.placeArea'))
        try:
            placePhotoName = self.uploadImageFile(request, 'contestPlace.placePhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if placePhotoName != 'img/NoImage.jpg':
            contestPlace.placePhoto = placePhotoName
        contestPlace.useDate = request.POST.get('contestPlace.useDate')
        contestPlace.placeDesc = request.POST.get('contestPlace.placeDesc')
        contestPlace.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台比赛场地添加
    def primaryKeyExist(self, placeNo):  # 判断主键是否存在
        try:
            ContestPlace.objects.get(placeNo=placeNo)
            return True
        except ContestPlace.DoesNotExist:
            return False

    def get(self,request):
        contestItems = ContestItem.objects.all()  # 获取所有比赛项目
        context = {
            'contestItems': contestItems,
        }

        # 渲染显示模板界面
        return render(request, 'ContestPlace/contestPlace_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        placeNo = request.POST.get('contestPlace.placeNo') # 判断场地编号是否存在
        if self.primaryKeyExist(placeNo):
            return JsonResponse({'success': False, 'message': '场地编号已经存在'})

        contestPlace = ContestPlace() # 新建一个比赛场地对象然后获取参数
        contestPlace.placeNo = placeNo
        contestPlace.contestItemObj = ContestItem.objects.get(classId=request.POST.get('contestPlace.contestItemObj.classId'))
        contestPlace.placeName = request.POST.get('contestPlace.placeName')
        contestPlace.placeArea = float(request.POST.get('contestPlace.placeArea'))
        try:
            contestPlace.placePhoto = self.uploadImageFile(request,'contestPlace.placePhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        contestPlace.useDate = request.POST.get('contestPlace.useDate')
        contestPlace.placeDesc = request.POST.get('contestPlace.placeDesc')
        contestPlace.save() # 保存比赛场地信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新比赛场地
    def get(self, request, placeNo):
        context = {'placeNo': placeNo}
        return render(request, 'ContestPlace/contestPlace_modify.html', context)


class ListView(BaseView):  # 后台比赛场地列表
    def get(self, request):
        # 使用模板
        return render(request, 'ContestPlace/contestPlace_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        placeNo = self.getStrParam(request, 'placeNo')
        contestItemObj_classId = self.getIntParam(request, 'contestItemObj.classId')
        placeName = self.getStrParam(request, 'placeName')
        useDate = self.getStrParam(request, 'useDate')
        # 然后条件组合查询过滤
        contestPlaces = ContestPlace.objects.all()
        if placeNo != '':
            contestPlaces = contestPlaces.filter(placeNo__contains=placeNo)
        if contestItemObj_classId != '0':
            contestPlaces = contestPlaces.filter(contestItemObj=contestItemObj_classId)
        if placeName != '':
            contestPlaces = contestPlaces.filter(placeName__contains=placeName)
        if useDate != '':
            contestPlaces = contestPlaces.filter(useDate__contains=useDate)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(contestPlaces, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        contestPlaces_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        contestPlaceList = []
        for contestPlace in contestPlaces_page:
            contestPlace = contestPlace.getJsonObj()
            contestPlaceList.append(contestPlace)
        # 构造模板页面需要的参数
        contestPlace_res = {
            'rows': contestPlaceList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示

PythonProject/templates/ContestPlace/contestPlace_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>比赛场地添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-12 wow fadeInLeft">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'ContestPlace:frontList' %}">比赛场地管理</a></li>
  			<li class="active">添加比赛场地</li>
		</ul>
		<div class="row">
			<div class="col-md-10">
		      	<form class="form-horizontal" name="contestPlaceAddForm" id="contestPlaceAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
				  <div class="form-group">
					 <label for="contestPlace_placeNo" class="col-md-2 text-right">场地编号:</label>
					 <div class="col-md-8"> 
					 	<input type="text" id="contestPlace_placeNo" name="contestPlace.placeNo" class="form-control" placeholder="请输入场地编号">
					 </div>
				  </div> 
				  <div class="form-group">
				  	 <label for="contestPlace_contestItemObj_classId" class="col-md-2 text-right">运动项目:</label>
				  	 <div class="col-md-8">
					    <select id="contestPlace_contestItemObj_classId" name="contestPlace.contestItemObj.classId" class="form-control">
                            {% for contestItem in contestItems %}
                            <option value="{{ contestItem.classId }}">{{ contestItem.className }}</option>
                            {% endfor %}
					    </select>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="contestPlace_placeName" class="col-md-2 text-right">场地名称:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="contestPlace_placeName" name="contestPlace.placeName" class="form-control" placeholder="请输入场地名称">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="contestPlace_placeArea" class="col-md-2 text-right">场地面积:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="contestPlace_placeArea" name="contestPlace.placeArea" class="form-control" placeholder="请输入场地面积">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="contestPlace_placePhoto" class="col-md-2 text-right">场地照片:</label>
				  	 <div class="col-md-8">
					    <img  class="img-responsive" id="contestPlace_placePhotoImg" border="0px"/><br/>
							    <input id="contestPlace_placePhoto" name="contestPlace.placePhoto" type="file" size="50" />
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="contestPlace_useDateDiv" class="col-md-2 text-right">投入使用时间:</label>
				  	 <div class="col-md-8">
		                <div id="contestPlace_useDateDiv" class="input-group date contestPlace_useDate col-md-12" data-link-field="contestPlace_useDate" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" id="contestPlace_useDate" name="contestPlace.useDate" size="16" type="text" value="" placeholder="请选择投入使用时间" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="contestPlace_placeDesc" class="col-md-2 text-right">场地描述:</label>
				  	 <div class="col-md-8">
					    <textarea id="contestPlace_placeDesc" name="contestPlace.placeDesc" rows="8" class="form-control" placeholder="请输入场地描述"></textarea>
					 </div>
				  </div>
		          <div class="form-group">
		             <span class="col-md-2"></span>
		             <span onclick="ajaxContestPlaceAdd();" class="btn btn-primary bottom5 top5">添加</span>
		          </div> 
		          <style>#contestPlaceAddForm .form-group {margin:5px;}  </style>  
				</form> 
			</div>
			<div class="col-md-2"></div> 
	    </div>
	</div>
</div>
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加比赛场地信息
	function ajaxContestPlaceAdd() { 
		//提交之前先验证表单
		$("#contestPlaceAddForm").data('bootstrapValidator').validate();
		if(!$("#contestPlaceAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'ContestPlace:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#contestPlaceAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证比赛场地添加表单字段
	$('#contestPlaceAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"contestPlace.placeNo": {
				validators: {
					notEmpty: {
						message: "场地编号不能为空",
					}
				}
			},
			"contestPlace.placeName": {
				validators: {
					notEmpty: {
						message: "场地名称不能为空",
					}
				}
			},
			"contestPlace.placeArea": {
				validators: {
					notEmpty: {
						message: "场地面积不能为空",
					},
					numeric: {
						message: "场地面积不正确"
					}
				}
			},
			"contestPlace.useDate": {
				validators: {
					notEmpty: {
						message: "投入使用时间不能为空",
					}
				}
			},
		}
	}); 
	//投入使用时间组件
	$('#contestPlace_useDateDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd',
		minView: 2,
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#contestPlaceAddForm').data('bootstrapValidator').updateStatus('contestPlace.useDate', 'NOT_VALIDATED',null).validateField('contestPlace.useDate');
	});
})
</script>
</body>
</html>

PythonProject/templates/ContestPlace/contestPlace_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看比赛场地详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'ContestPlace:frontList' %}">比赛场地信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">场地编号:</div>
		<div class="col-md-10 col-xs-6">{{ contestPlace.placeNo }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">运动项目:</div>
		<div class="col-md-10 col-xs-6">{{ contestPlace.contestItemObj.className }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">场地名称:</div>
		<div class="col-md-10 col-xs-6">{{ contestPlace.placeName }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">场地面积:</div>
		<div class="col-md-10 col-xs-6">{{ contestPlace.placeArea }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">场地照片:</div>
		<div class="col-md-10 col-xs-6"><img class="img-responsive" src="{{ contestPlace.placePhoto.url }}"  border="0px"/></div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">投入使用时间:</div>
		<div class="col-md-10 col-xs-6">{{ contestPlace.useDate }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">场地描述:</div>
		<div class="col-md-10 col-xs-6">{{ contestPlace.placeDesc }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
