PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^ContestItem/', include('apps.ContestItem.urls', namespace='ContestItem')),  # 比赛项目模块
    url(r'^Contest/', include('apps.Contest.urls', namespace='Contest')),  # 比赛模块
    url(r'^SignUp/', include('apps.SignUp.urls', namespace='SignUp')),  # 学生报名模块
    url(r'^Court/', include('apps.Court.urls', namespace='Court')),  # 赛场安排模块
    url(r'^ContestPlace/', include('apps.ContestPlace.urls', namespace='ContestPlace')),  # 比赛场地模块
    url(r'^Jifen/', include('apps.Jifen.urls', namespace='Jifen')),  # 比赛积分模块
    url(r'^DoctorTeam/', include('apps.DoctorTeam.urls', namespace='DoctorTeam')),  # 医护团队模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/DoctorTeam/urls.py
from apps.DoctorTeam.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'DoctorTeam'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<teamId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<teamId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<teamId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<teamId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,\
    PersonStatisticView,CourtStatisticView,JifenStatisticView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^personStatistic$', PersonStatisticView.as_view(), name='main'),  # 报名人数统计
    url(r'^courtStatistic$', CourtStatisticView.as_view(), name='main'),  # 场次数量统计
    url(r'^jifenStatistic$', JifenStatisticView.as_view(), name='main'),  # 比赛积分统计
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/DoctorTeam/models.py
from django.db import models
from tinymce.models import HTMLField


class DoctorTeam(models.Model):
    teamId = models.AutoField(primary_key=True, verbose_name='团队id')
    teamName = models.CharField(max_length=20, default='', verbose_name='团队名称')
    teamPhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='团队照片')
    useState = models.CharField(max_length=20, default='', verbose_name='使用状态')
    bornDate = models.CharField(max_length=20, default='', verbose_name='成立日期')
    chargeMan = models.CharField(max_length=20, default='', verbose_name='负责人')
    connectPhone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    teamDesc = HTMLField(max_length=5000, verbose_name='团队介绍')

    class Meta:
        db_table = 't_DoctorTeam'
        verbose_name = '医护团队信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        doctorTeam = {
            'teamId': self.teamId,
            'teamName': self.teamName,
            'teamPhoto': self.teamPhoto.url,
            'useState': self.useState,
            'bornDate': self.bornDate,
            'chargeMan': self.chargeMan,
            'connectPhone': self.connectPhone,
            'teamDesc': self.teamDesc,
        }
        return doctorTeam


PythonProject/apps/DoctorTeam/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.DoctorTeam.models import DoctorTeam
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台医护团队添加
    def get(self,request):

        # 使用模板
        return render(request, 'DoctorTeam/doctorTeam_frontAdd.html')

    def post(self, request):
        doctorTeam = DoctorTeam() # 新建一个医护团队对象然后获取参数
        doctorTeam.teamName = request.POST.get('doctorTeam.teamName')
        try:
            doctorTeam.teamPhoto = self.uploadImageFile(request,'doctorTeam.teamPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        doctorTeam.useState = request.POST.get('doctorTeam.useState')
        doctorTeam.bornDate = request.POST.get('doctorTeam.bornDate')
        doctorTeam.chargeMan = request.POST.get('doctorTeam.chargeMan')
        doctorTeam.connectPhone = request.POST.get('doctorTeam.connectPhone')
        doctorTeam.teamDesc = request.POST.get('doctorTeam.teamDesc')
        doctorTeam.save() # 保存医护团队信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改医护团队
    def get(self, request, teamId):
        context = {'teamId': teamId}
        return render(request, 'DoctorTeam/doctorTeam_frontModify.html', context)


class FrontListView(BaseView):  # 前台医护团队查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        teamName = self.getStrParam(request, 'teamName')
        useState = self.getStrParam(request, 'useState')
        bornDate = self.getStrParam(request, 'bornDate')
        # 然后条件组合查询过滤
        doctorTeams = DoctorTeam.objects.all()
        if teamName != '':
            doctorTeams = doctorTeams.filter(teamName__contains=teamName)
        if useState != '':
            doctorTeams = doctorTeams.filter(useState__contains=useState)
        if bornDate != '':
            doctorTeams = doctorTeams.filter(bornDate__contains=bornDate)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(doctorTeams, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        doctorTeams_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'doctorTeams_page': doctorTeams_page,
            'teamName': teamName,
            'useState': useState,
            'bornDate': bornDate,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'DoctorTeam/doctorTeam_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示医护团队详情页
    def get(self, request, teamId):
        # 查询需要显示的医护团队对象
        doctorTeam = DoctorTeam.objects.get(teamId=teamId)
        context = {
            'doctorTeam': doctorTeam
        }
        # 渲染模板显示
        return render(request, 'DoctorTeam/doctorTeam_frontshow.html', context)


class ListAllView(View): # 前台查询所有医护团队
    def get(self,request):
        doctorTeams = DoctorTeam.objects.all()
        doctorTeamList = []
        for doctorTeam in doctorTeams:
            doctorTeamObj = {
                'teamId': doctorTeam.teamId,
                'teamName': doctorTeam.teamName,
            }
            doctorTeamList.append(doctorTeamObj)
        return JsonResponse(doctorTeamList, safe=False)


class UpdateView(BaseView):  # Ajax方式医护团队更新
    def get(self, request, teamId):
        # GET方式请求查询医护团队对象并返回医护团队json格式
        doctorTeam = DoctorTeam.objects.get(teamId=teamId)
        return JsonResponse(doctorTeam.getJsonObj())

    def post(self, request, teamId):
        # POST方式提交医护团队修改信息更新到数据库
        doctorTeam = DoctorTeam.objects.get(teamId=teamId)
        doctorTeam.teamName = request.POST.get('doctorTeam.teamName')
        try:
            teamPhotoName = self.uploadImageFile(request, 'doctorTeam.teamPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if teamPhotoName != 'img/NoImage.jpg':
            doctorTeam.teamPhoto = teamPhotoName
        doctorTeam.useState = request.POST.get('doctorTeam.useState')
        doctorTeam.bornDate = request.POST.get('doctorTeam.bornDate')
        doctorTeam.chargeMan = request.POST.get('doctorTeam.chargeMan')
        doctorTeam.connectPhone = request.POST.get('doctorTeam.connectPhone')
        doctorTeam.teamDesc = request.POST.get('doctorTeam.teamDesc')
        doctorTeam.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台医护团队添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'DoctorTeam/doctorTeam_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        doctorTeam = DoctorTeam() # 新建一个医护团队对象然后获取参数
        doctorTeam.teamName = request.POST.get('doctorTeam.teamName')
        try:
            doctorTeam.teamPhoto = self.uploadImageFile(request,'doctorTeam.teamPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        doctorTeam.useState = request.POST.get('doctorTeam.useState')
        doctorTeam.bornDate = request.POST.get('doctorTeam.bornDate')
        doctorTeam.chargeMan = request.POST.get('doctorTeam.chargeMan')
        doctorTeam.connectPhone = request.POST.get('doctorTeam.connectPhone')
        doctorTeam.teamDesc = request.POST.get('doctorTeam.teamDesc')
        doctorTeam.save() # 保存医护团队信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新医护团队
    def get(self, request, teamId):
        context = {'teamId': teamId}
        return render(request, 'DoctorTeam/doctorTeam_modify.html', context)


class ListView(BaseView):  # 后台医护团队列表
    def get(self, request):
        # 使用模板
        return render(request, 'DoctorTeam/doctorTeam_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        teamName = self.getStrParam(request, 'teamName')
        useState = self.getStrParam(request, 'useState')
        bornDate = self.getStrParam(request, 'bornDate')
        # 然后条件组合查询过滤
        doctorTeams = DoctorTeam.objects.all()
        if teamName != '':
            doctorTeams = doctorTeams.filter(teamName__contains=teamName)
        if useState != '':
            doctorTeams = doctorTeams.filter(useState__contains=useState)
        if bornDate != '':
            doctorTeams = doctorTeams.filter(bornDate__contains=bornDate)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(doctorTeams, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        doctorTeams_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        doctorTeamList = []
        for doctorTeam in doctorTeams_page:
            doctorTeam = doctorTeam.getJsonObj()
            doctorTeamList.append(doctorTeam)
        # 构造模板页面需要的参数
        doctorTeam_res = {
            'rows': doctorTeamList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(doctorTeam_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除医护团队信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        teamIds = self.getStrParam(request, 'teamIds')
        teamIds = teamIds.split(',')
        count = 0
        try:
            for teamId in teamIds:
                DoctorTeam.objects.get(teamId=teamId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出医护团队信息到excel并下载
    def get(self, request):
        # 收集查询参数
        teamName = self.getStrParam(request, 'teamName')
        useState = self.getStrParam(request, 'useState')
        bornDate = self.getStrParam(request, 'bornDate')
        # 然后条件组合查询过滤
        doctorTeams = DoctorTeam.objects.all()
        if teamName != '':
            doctorTeams = doctorTeams.filter(teamName__contains=teamName)
        if useState != '':
            doctorTeams = doctorTeams.filter(useState__contains=useState)
        if bornDate != '':
            doctorTeams = doctorTeams.filter(bornDate__contains=bornDate)
        #将查询结果集转换成列表
        doctorTeamList = []
        for doctorTeam in doctorTeams:
            doctorTeam = doctorTeam.getJsonObj()
            doctorTeamList.append(doctorTeam)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(doctorTeamList)
        # 设置要导入到excel的列
        columns_map = {
            'teamId': '团队id',
            'teamName': '团队名称',
            'useState': '使用状态',
            'bornDate': '成立日期',
            'chargeMan': '负责人',
            'connectPhone': '联系电话',
        }
        pf = pf[columns_map.keys()]

PythonProject/templates/DoctorTeam/doctorTeam_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>医护团队添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-12 wow fadeInLeft">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'DoctorTeam:frontList' %}">医护团队管理</a></li>
  			<li class="active">添加医护团队</li>
		</ul>
		<div class="row">
			<div class="col-md-10">
		      	<form class="form-horizontal" name="doctorTeamAddForm" id="doctorTeamAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
				  <div class="form-group">
				  	 <label for="doctorTeam_teamName" class="col-md-2 text-right">团队名称:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="doctorTeam_teamName" name="doctorTeam.teamName" class="form-control" placeholder="请输入团队名称">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="doctorTeam_teamPhoto" class="col-md-2 text-right">团队照片:</label>
				  	 <div class="col-md-8">
					    <img  class="img-responsive" id="doctorTeam_teamPhotoImg" border="0px"/><br/>
							    <input id="doctorTeam_teamPhoto" name="doctorTeam.teamPhoto" type="file" size="50" />
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="doctorTeam_useState" class="col-md-2 text-right">使用状态:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="doctorTeam_useState" name="doctorTeam.useState" class="form-control" placeholder="请输入使用状态">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="doctorTeam_bornDateDiv" class="col-md-2 text-right">成立日期:</label>
				  	 <div class="col-md-8">
		                <div id="doctorTeam_bornDateDiv" class="input-group date doctorTeam_bornDate col-md-12" data-link-field="doctorTeam_bornDate" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" id="doctorTeam_bornDate" name="doctorTeam.bornDate" size="16" type="text" value="" placeholder="请选择成立日期" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="doctorTeam_chargeMan" class="col-md-2 text-right">负责人:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="doctorTeam_chargeMan" name="doctorTeam.chargeMan" class="form-control" placeholder="请输入负责人">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="doctorTeam_connectPhone" class="col-md-2 text-right">联系电话:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="doctorTeam_connectPhone" name="doctorTeam.connectPhone" class="form-control" placeholder="请输入联系电话">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="doctorTeam_teamDesc" class="col-md-2 text-right">团队介绍:</label>
				  	 <div class="col-md-8">
							    <textarea name="doctorTeam.teamDesc" id="doctorTeam_teamDesc" style="width:100%;height:300px;"></textarea>
					 </div>
				  </div>
		          <div class="form-group">
		             <span class="col-md-2"></span>
		             <span onclick="ajaxDoctorTeamAdd();" class="btn btn-primary bottom5 top5">添加</span>
		          </div> 
		          <style>#doctorTeamAddForm .form-group {margin:5px;}  </style>  
				</form> 
			</div>
			<div class="col-md-2"></div> 
	    </div>
	</div>
</div>
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script>
    //实例化团队介绍编辑器
    tinyMCE.init({
        selector: "#doctorTeam_teamDesc",
        theme: 'advanced',
        language: "zh",
        strict_loading_mode: 1,
    });
	//提交添加医护团队信息
	function ajaxDoctorTeamAdd() { 
	    $("#doctorTeam_teamDesc").text(tinyMCE.editors['doctorTeam_teamDesc'].getContent());
		//提交之前先验证表单
		$("#doctorTeamAddForm").data('bootstrapValidator').validate();
		if(!$("#doctorTeamAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'DoctorTeam:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#doctorTeamAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证医护团队添加表单字段
	$('#doctorTeamAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"doctorTeam.teamName": {
				validators: {
					notEmpty: {
						message: "团队名称不能为空",
					}
				}
			},
			"doctorTeam.useState": {
				validators: {
					notEmpty: {
						message: "使用状态不能为空",
					}
				}
			},
			"doctorTeam.bornDate": {
				validators: {
					notEmpty: {
						message: "成立日期不能为空",
					}
				}
			},
			"doctorTeam.chargeMan": {
				validators: {
					notEmpty: {
						message: "负责人不能为空",
					}
				}
			},
			"doctorTeam.connectPhone": {
				validators: {
					notEmpty: {
						message: "联系电话不能为空",
					}
				}
			},
		}
	}); 
	//成立日期组件
	$('#doctorTeam_bornDateDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd',
		minView: 2,
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#doctorTeamAddForm').data('bootstrapValidator').updateStatus('doctorTeam.bornDate', 'NOT_VALIDATED',null).validateField('doctorTeam.bornDate');
	});
})
</script>
</body>
</html>

PythonProject/templates/DoctorTeam/doctorTeam_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看医护团队详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'DoctorTeam:frontList' %}">医护团队信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">团队id:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.teamId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">团队名称:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.teamName }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">团队照片:</div>
		<div class="col-md-10 col-xs-6"><img class="img-responsive" src="{{ doctorTeam.teamPhoto.url }}"  border="0px"/></div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">使用状态:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.useState }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">成立日期:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.bornDate }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">负责人:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.chargeMan }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">联系电话:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.connectPhone }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">团队介绍:</div>
		<div class="col-md-10 col-xs-6">{{ doctorTeam.teamDesc | safe  }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
